/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayoutChannelSlugRouteImport } from './routes/playout.$channelSlug'
import { Route as EmbedChannelSlugRouteImport } from './routes/embed.$channelSlug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedPlayoutRouteImport } from './routes/_authenticated/playout'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as ApiCronAutopilotRouteImport } from './routes/api/cron/autopilot'
import { Route as AuthenticatedChannelsChannelSlugSettingsRouteImport } from './routes/_authenticated/channels.$channelSlug.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayoutChannelSlugRoute = PlayoutChannelSlugRouteImport.update({
  id: '/playout/$channelSlug',
  path: '/playout/$channelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedChannelSlugRoute = EmbedChannelSlugRouteImport.update({
  id: '/embed/$channelSlug',
  path: '/embed/$channelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayoutRoute = AuthenticatedPlayoutRouteImport.update({
  id: '/playout',
  path: '/playout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiCronAutopilotRoute = ApiCronAutopilotRouteImport.update({
  id: '/api/cron/autopilot',
  path: '/api/cron/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChannelsChannelSlugSettingsRoute =
  AuthenticatedChannelsChannelSlugSettingsRouteImport.update({
    id: '/channels/$channelSlug/settings',
    path: '/channels/$channelSlug/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/playout': typeof AuthenticatedPlayoutRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/embed/$channelSlug': typeof EmbedChannelSlugRoute
  '/playout/$channelSlug': typeof PlayoutChannelSlugRoute
  '/api/cron/autopilot': typeof ApiCronAutopilotRoute
  '/channels/$channelSlug/settings': typeof AuthenticatedChannelsChannelSlugSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/playout': typeof AuthenticatedPlayoutRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/embed/$channelSlug': typeof EmbedChannelSlugRoute
  '/playout/$channelSlug': typeof PlayoutChannelSlugRoute
  '/api/cron/autopilot': typeof ApiCronAutopilotRoute
  '/channels/$channelSlug/settings': typeof AuthenticatedChannelsChannelSlugSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/playout': typeof AuthenticatedPlayoutRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/embed/$channelSlug': typeof EmbedChannelSlugRoute
  '/playout/$channelSlug': typeof PlayoutChannelSlugRoute
  '/api/cron/autopilot': typeof ApiCronAutopilotRoute
  '/_authenticated/channels/$channelSlug/settings': typeof AuthenticatedChannelsChannelSlugSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/collections'
    | '/playout'
    | '/schedules'
    | '/settings'
    | '/embed/$channelSlug'
    | '/playout/$channelSlug'
    | '/api/cron/autopilot'
    | '/channels/$channelSlug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/collections'
    | '/playout'
    | '/schedules'
    | '/settings'
    | '/embed/$channelSlug'
    | '/playout/$channelSlug'
    | '/api/cron/autopilot'
    | '/channels/$channelSlug/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/collections'
    | '/_authenticated/playout'
    | '/_authenticated/schedules'
    | '/_authenticated/settings'
    | '/embed/$channelSlug'
    | '/playout/$channelSlug'
    | '/api/cron/autopilot'
    | '/_authenticated/channels/$channelSlug/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  EmbedChannelSlugRoute: typeof EmbedChannelSlugRoute
  PlayoutChannelSlugRoute: typeof PlayoutChannelSlugRoute
  ApiCronAutopilotRoute: typeof ApiCronAutopilotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playout/$channelSlug': {
      id: '/playout/$channelSlug'
      path: '/playout/$channelSlug'
      fullPath: '/playout/$channelSlug'
      preLoaderRoute: typeof PlayoutChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$channelSlug': {
      id: '/embed/$channelSlug'
      path: '/embed/$channelSlug'
      fullPath: '/embed/$channelSlug'
      preLoaderRoute: typeof EmbedChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playout': {
      id: '/_authenticated/playout'
      path: '/playout'
      fullPath: '/playout'
      preLoaderRoute: typeof AuthenticatedPlayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/cron/autopilot': {
      id: '/api/cron/autopilot'
      path: '/api/cron/autopilot'
      fullPath: '/api/cron/autopilot'
      preLoaderRoute: typeof ApiCronAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/channels/$channelSlug/settings': {
      id: '/_authenticated/channels/$channelSlug/settings'
      path: '/channels/$channelSlug/settings'
      fullPath: '/channels/$channelSlug/settings'
      preLoaderRoute: typeof AuthenticatedChannelsChannelSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedPlayoutRoute: typeof AuthenticatedPlayoutRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChannelsChannelSlugSettingsRoute: typeof AuthenticatedChannelsChannelSlugSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedPlayoutRoute: AuthenticatedPlayoutRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChannelsChannelSlugSettingsRoute:
    AuthenticatedChannelsChannelSlugSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  EmbedChannelSlugRoute: EmbedChannelSlugRoute,
  PlayoutChannelSlugRoute: PlayoutChannelSlugRoute,
  ApiCronAutopilotRoute: ApiCronAutopilotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
